import { join, resolve, dirname } from "path";
import { existsSync, mkdirSync, copyFileSync, rmSync } from "fs";
import { atomicWriteText } from "./fs-utils";

// ── Paths ───────────────────────────────────────────────────────────────────
// Pi auto-discovers extensions from `.pi/extensions/*.ts` and skills from
// `.pi/skills/*/SKILL.md`, so simply writing these files wires Mink in — no
// `.pi/settings.json` edit required, which keeps us from clobbering the user's
// own Pi configuration.

export function piExtensionPath(cwd: string): string {
  return join(cwd, ".pi", "extensions", "mink.ts");
}

export function piGuidanceSkillPath(cwd: string): string {
  return join(cwd, ".pi", "skills", "mink", "SKILL.md");
}

export function piNoteSkillPath(cwd: string): string {
  return join(cwd, ".pi", "skills", "mink-note", "SKILL.md");
}

// ── Extension source ─────────────────────────────────────────────────────────

/**
 * Generate the Pi adapter extension. Like the Claude hook wiring, the `mink`
 * invocation is templated: an installed package resolves the portable `mink`
 * bin shim (so a committed `.pi/` works across machines), while source-dev mode
 * falls back to `bun run <abs cli.ts>`.
 *
 * The adapter shells out to the same `mink` lifecycle commands every other host
 * uses, translating Pi's event/tool shapes into Mink's canonical payload. It is
 * deliberately defensive: it never throws into Pi, never blocks a tool, and
 * times out fast — matching the safety contract of the Claude hooks.
 */
export function buildPiExtension(cliPath: string): string {
  const isTsSource = cliPath.endsWith(".ts");
  const cmd = isTsSource ? "bun" : "mink";
  const baseArgs = isTsSource ? JSON.stringify(["run", cliPath]) : "[]";

  return `// AUTO-GENERATED by \`mink init\`. Do not edit — re-run \`mink init\` to refresh.
//
// Mink adapter for the Pi coding agent. Routes Pi lifecycle and tool events
// into the \`mink\` CLI so Pi shares the same ~/.mink state, file index, ledger,
// and wiki as every other assistant wired to this project.
//
// VERIFY-ON-UPGRADE: the tool input field names (file_path / path, content,
// new_string), the tool-result content location, and the advisory surfacing
// call are written against Pi's documented extension API. They are accessed
// defensively (optional chaining + fallbacks) so a rename in a future Pi
// release degrades to "no advisory" rather than breaking. If Pi changes these,
// adjust toolInfo(), resultContent(), and surface() below.

import { spawn } from "node:child_process";

const MINK_CMD = ${JSON.stringify(cmd)};
const MINK_BASE_ARGS = ${baseArgs};
const TIMEOUT_MS = 5000;

function runMink(sub, payload, cwd) {
  return new Promise((res) => {
    let done = false;
    const finish = (out) => {
      if (done) return;
      done = true;
      res(out);
    };
    try {
      const child = spawn(MINK_CMD, [...MINK_BASE_ARGS, sub], {
        cwd,
        stdio: ["pipe", "ignore", "pipe"],
      });
      let stderr = "";
      child.stderr?.on("data", (d) => {
        stderr += d.toString();
      });
      child.on("error", () => finish(""));
      child.on("close", () => finish(stderr.trim()));
      const timer = setTimeout(() => {
        try {
          child.kill();
        } catch {}
        finish("");
      }, TIMEOUT_MS);
      timer.unref?.();
      try {
        child.stdin?.end(payload ? JSON.stringify(payload) : "");
      } catch {}
    } catch {
      finish("");
    }
  });
}

// Resolve Pi's tool name + arguments to Mink's canonical operation. Only the
// three file operations matter; anything else returns null and is ignored.
function toolInfo(event) {
  const name = String(event?.toolName ?? event?.tool ?? event?.name ?? "").toLowerCase();
  const input = event?.input ?? event?.arguments ?? event?.args ?? {};
  const filePath = input.file_path ?? input.path ?? input.filePath;
  if (!filePath) return null;
  if (name === "read") return { op: "read", filePath };
  if (name === "write") return { op: "write", filePath, content: input.content ?? input.text ?? "" };
  if (name === "edit")
    return {
      op: "edit",
      filePath,
      newString: input.new_string ?? input.newText ?? input.replacement ?? "",
    };
  return null;
}

function resultContent(event) {
  const r = event?.result ?? event?.output ?? event?.toolResult;
  if (typeof r === "string") return r;
  if (r && typeof r.content === "string") return r.content;
  return null;
}

function prePayload(info) {
  if (info.op === "read")
    return { sub: "pre-read", payload: { tool_name: "Read", tool_input: { file_path: info.filePath } } };
  if (info.op === "write")
    return {
      sub: "pre-write",
      payload: { tool_name: "Write", tool_input: { file_path: info.filePath, content: info.content } },
    };
  return {
    sub: "pre-write",
    payload: { tool_name: "Edit", tool_input: { file_path: info.filePath, new_string: info.newString } },
  };
}

function postPayload(info, content) {
  if (info.op === "read")
    return {
      sub: "post-read",
      payload: {
        tool_name: "Read",
        tool_input: { file_path: info.filePath },
        tool_output: content == null ? undefined : { content },
      },
    };
  if (info.op === "write")
    return {
      sub: "post-write",
      payload: { tool_name: "Write", tool_input: { file_path: info.filePath, content: info.content } },
    };
  return {
    sub: "post-write",
    payload: { tool_name: "Edit", tool_input: { file_path: info.filePath, new_string: info.newString } },
  };
}

export default function (pi) {
  const cwd = pi?.ctx?.cwd || process.cwd();
  const pending = new Map();
  const keyOf = (event) => event?.toolCallId ?? event?.id ?? event?.callId ?? "";

  // Surface Mink's advisories into the model's context, mirroring how the
  // Claude integration feeds hook stderr back to the assistant.
  const surface = (text) => {
    if (!text) return;
    try {
      if (typeof pi.sendMessage === "function") {
        pi.sendMessage(text);
        return;
      }
    } catch {}
    try {
      pi.ui?.notify?.(text, "info");
    } catch {}
  };

  pi.on?.("session_start", () => {
    void runMink("session-start", null, cwd);
  });
  pi.on?.("agent_end", () => {
    void runMink("session-stop", null, cwd);
  });
  pi.on?.("session_shutdown", () => {
    void runMink("session-stop", null, cwd);
  });

  pi.on?.("tool_call", async (event) => {
    const info = toolInfo(event);
    if (!info) return;
    const { sub, payload } = prePayload(info);
    const advisory = await runMink(sub, payload, cwd);
    if (advisory) pending.set(keyOf(event), advisory);
  });

  pi.on?.("tool_result", async (event) => {
    const info = toolInfo(event);
    if (!info) return;
    const { sub, payload } = postPayload(info, resultContent(event));
    const post = await runMink(sub, payload, cwd);
    const pre = pending.get(keyOf(event)) ?? "";
    pending.delete(keyOf(event));
    surface([pre, post].filter(Boolean).join("\\n"));
  });
}
`;
}

// ── Guidance skill ───────────────────────────────────────────────────────────
// Pi has no automatic project-rules file (CLAUDE.md / AGENTS.md equivalent), so
// the guidance Mink gives the assistant is delivered as a Pi skill instead.

const PI_GUIDANCE_SKILL = `---
name: mink
description: Mink context management is active in this project. Read this to understand how Mink memory, write enforcement, and note capture work under Pi.
---

# Mink — context management for this project

This project uses **Mink** (\`@drewpayment/mink\`) for cross-session context management.

## How it works
- Mink runs automatically through a Pi extension at \`.pi/extensions/mink.ts\` that hooks session start/stop and every read/edit/write tool call.
- All state lives in \`~/.mink/\` on the user's machine — **not** in this repository. Do not create or write to any in-repo state directory (no \`.wolf/\`, \`.mink/\`, etc.).
- Read intelligence, write enforcement, bug memory, and the token ledger are handled by the extension. You do not need to manually read or update any state files.
- Mink shares one \`~/.mink/\` state across every assistant wired to this project, so history is unified whether the user runs Pi or another assistant.

## When to act on Mink
- If the user asks to "save a note", "remember this", "log this to my wiki", or similar, use the \`mink-note\` skill (\`/skill:mink-note\`) — it captures into the user's \`~/.mink/\` vault.
- If the extension surfaces a learning, past bug, or repeat-read warning in context, treat that as authoritative project memory and follow it.
- The \`mink dashboard\` and \`mink agent\` commands are user tools — do not invoke them on the user's behalf.
`;

function resolveSkillsSourceDir(): string {
  // Walk up until we find a package root that contains skills/ — works from
  // src/core/agent-pi.ts (dev) and dist/cli.js (installed), which sit at
  // different depths relative to the package root.
  let dir = dirname(new URL(import.meta.url).pathname);
  while (true) {
    if (existsSync(join(dir, "package.json")) && existsSync(join(dir, "skills"))) {
      return join(dir, "skills");
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(dirname(new URL(import.meta.url).pathname), "../../skills");
}

export interface PiInstallResult {
  extensionPath: string;
  guidancePath: string;
  notePath: string | null;
}

export function installPi(cwd: string, cliPath: string): PiInstallResult {
  const extensionPath = piExtensionPath(cwd);
  mkdirSync(dirname(extensionPath), { recursive: true });
  atomicWriteText(extensionPath, buildPiExtension(cliPath));

  const guidancePath = piGuidanceSkillPath(cwd);
  mkdirSync(dirname(guidancePath), { recursive: true });
  atomicWriteText(guidancePath, PI_GUIDANCE_SKILL);

  // Mirror the note-capture skill into Pi's skill directory so the single
  // source of truth (skills/mink-note) is reused rather than duplicated.
  let notePath: string | null = null;
  try {
    const src = join(resolveSkillsSourceDir(), "mink-note", "SKILL.md");
    if (existsSync(src)) {
      notePath = piNoteSkillPath(cwd);
      mkdirSync(dirname(notePath), { recursive: true });
      copyFileSync(src, notePath);
    }
  } catch {
    // Note skill is non-critical — the extension and guidance still work.
    notePath = null;
  }

  return { extensionPath, guidancePath, notePath };
}

export function removePi(cwd: string): void {
  for (const p of [
    piExtensionPath(cwd),
    join(cwd, ".pi", "skills", "mink"),
    join(cwd, ".pi", "skills", "mink-note"),
  ]) {
    try {
      rmSync(p, { recursive: true, force: true });
    } catch {
      // best-effort
    }
  }
}
