import { join, resolve, dirname } from "path";
import { existsSync, mkdirSync, copyFileSync, rmSync } from "fs";
import { atomicWriteText } from "./fs-utils";

// ── Paths ───────────────────────────────────────────────────────────────────
// Pi auto-discovers extensions from `.pi/extensions/*.ts` and skills from
// `.pi/skills/*/SKILL.md`, so simply writing these files wires Mink in — no
// `.pi/settings.json` edit required, which keeps us from clobbering the user's
// own Pi configuration.

export function piExtensionPath(cwd: string): string {
  return join(cwd, ".pi", "extensions", "mink.ts");
}

export function piGuidanceSkillPath(cwd: string): string {
  return join(cwd, ".pi", "skills", "mink", "SKILL.md");
}

export function piNoteSkillPath(cwd: string): string {
  return join(cwd, ".pi", "skills", "mink-note", "SKILL.md");
}

// ── Extension source ─────────────────────────────────────────────────────────

/**
 * Generate the Pi adapter extension. Like the Claude hook wiring, the `mink`
 * invocation is templated: an installed package resolves the portable `mink`
 * bin shim (so a committed `.pi/` works across machines), while source-dev mode
 * falls back to `bun run <abs cli.ts>`.
 *
 * The adapter shells out to the same `mink` lifecycle commands every other host
 * uses, translating Pi's event/tool shapes into Mink's canonical payload. It is
 * deliberately defensive: it never throws into Pi, never blocks a tool, and
 * times out fast — matching the safety contract of the Claude hooks.
 */
export function buildPiExtension(cliPath: string): string {
  const isTsSource = cliPath.endsWith(".ts");
  const cmd = isTsSource ? "bun" : "mink";
  const baseArgs = isTsSource ? JSON.stringify(["run", cliPath]) : "[]";

  return `// AUTO-GENERATED by \`mink init\`. Do not edit — re-run \`mink init\` to refresh.
//
// Mink adapter for the Pi coding agent. Routes Pi lifecycle and tool events
// into the \`mink\` CLI so Pi shares the same ~/.mink state, file index, ledger,
// and wiki as every other assistant wired to this project.
//
// Field shapes confirmed against pi source (earendil-works/pi,
// packages/coding-agent): read params {path, offset, limit}; write {path,
// content}; edit {path, edits:[{oldText,newText}]} (with legacy file_path /
// top-level oldText,newText). tool_call/tool_result events expose toolName,
// toolCallId, input; tool_result also exposes content (a content-block array),
// details, isError. Advisories are surfaced by returning a modified result from
// the tool_result handler — the documented mechanism; that same return path
// SUBSTITUTES a reversible compressed result whenever a hook prints Claude
// Code's { hookSpecificOutput: { updatedToolOutput } } envelope on stdout
// (tool-output compression, spec 22 — Bash/Grep/Glob/MCP via post-tool, large
// whole-file reads via post-read; the original is retrievable with
// \`mink retrieve\`). pi.exec has no stdin, so the canonical payload is piped to
// \`mink\` via a spawned child process. Every host-API access is defensive: the
// adapter never throws into Pi or blocks a tool — a failure degrades to "no
// advisory" and the original, uncompressed output.

import { spawn } from "node:child_process";

const MINK_CMD = ${JSON.stringify(cmd)};
const MINK_BASE_ARGS = ${baseArgs};
const TIMEOUT_MS = 5000;

// Spawn a \`mink\` subcommand, pipe the canonical payload to its stdin, and
// collect BOTH streams: stdout carries a compression replacement
// (Claude Code's { hookSpecificOutput: { updatedToolOutput } } envelope) and
// stderr carries human-visible advisories. Always resolves to { out, err } —
// any failure or timeout degrades to empty strings, never a rejection.
function runMink(sub, payload, cwd) {
  return new Promise((res) => {
    let done = false;
    const finish = (out, err) => {
      if (done) return;
      done = true;
      res({ out: (out || "").trim(), err: (err || "").trim() });
    };
    try {
      const child = spawn(MINK_CMD, [...MINK_BASE_ARGS, sub], {
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
      let stdout = "";
      let stderr = "";
      child.stdout?.on("data", (d) => {
        stdout += d.toString();
      });
      child.stderr?.on("data", (d) => {
        stderr += d.toString();
      });
      child.on("error", () => finish("", ""));
      child.on("close", () => finish(stdout, stderr));
      const timer = setTimeout(() => {
        try {
          child.kill();
        } catch {}
        finish("", "");
      }, TIMEOUT_MS);
      timer.unref?.();
      try {
        child.stdin?.end(payload ? JSON.stringify(payload) : "");
      } catch {}
    } catch {
      finish("", "");
    }
  });
}

// Pi's edit tool takes an array of { oldText, newText } replacements (legacy
// inputs may put oldText/newText/new_string at the top level). Concatenate the
// replacement text so Mink's write-enforcement sees everything being written.
function editNewText(input) {
  if (Array.isArray(input.edits)) {
    return input.edits
      .map((e) => e?.newText ?? e?.new_string ?? "")
      .filter(Boolean)
      .join("\\n");
  }
  return input.newText ?? input.new_string ?? input.replacement ?? "";
}

// Resolve Pi's tool name + arguments to Mink's canonical operation. Only the
// three file operations matter; anything else returns null and is ignored.
function toolInfo(event) {
  const name = String(event?.toolName ?? event?.tool ?? event?.name ?? "").toLowerCase();
  const input = event?.input ?? event?.arguments ?? {};
  const filePath = input.path ?? input.file_path ?? input.filePath;
  if (!filePath) return null;
  if (name === "read") return { op: "read", filePath };
  if (name === "write") return { op: "write", filePath, content: input.content ?? input.text ?? "" };
  if (name === "edit") return { op: "edit", filePath, newString: editNewText(input) };
  return null;
}

// A tool_result's content is an array of content blocks ({ type, text }); pull
// the text out so Mink's post-read can estimate tokens from real content.
function resultContent(event) {
  const c = event?.content;
  if (typeof c === "string") return c;
  if (Array.isArray(c)) {
    const text = c
      .map((b) => (typeof b === "string" ? b : b?.text ?? ""))
      .filter(Boolean)
      .join("\\n");
    return text || null;
  }
  return null;
}

// Parse a hook's stdout for a reversible compression replacement. Mink's
// post-read/post-tool hooks print Claude Code's
// { hookSpecificOutput: { updatedToolOutput } } envelope on stdout; under Pi we
// read it here and substitute it into the tool result. Empty/non-JSON → null.
function parseReplacement(out) {
  if (!out) return null;
  try {
    const j = JSON.parse(out);
    const r = j?.hookSpecificOutput?.updatedToolOutput;
    return typeof r === "string" ? r : null;
  } catch {
    return null;
  }
}

// Map a Pi non-file tool to the canonical Mink tool name the post-tool
// compression hook accepts (Bash/Grep/Glob, or an mcp__* passthrough). Pi's
// built-in tool names aren't all pinned, so map common shell/search aliases and
// return null for anything Mink doesn't compress — those pass through untouched.
function compressibleName(event) {
  const raw = String(event?.toolName ?? event?.tool ?? event?.name ?? "");
  const name = raw.toLowerCase();
  if (name.startsWith("mcp__")) return raw;
  if (name.startsWith("mcp")) return "mcp__" + raw;
  if (name === "bash" || name === "shell" || name === "exec" || name === "command" || name === "run")
    return "Bash";
  if (name === "grep" || name === "search" || name === "ripgrep" || name === "rg")
    return "Grep";
  if (name === "glob" || name === "find") return "Glob";
  return null;
}

function prePayload(info) {
  if (info.op === "read")
    return { sub: "pre-read", payload: { tool_name: "Read", tool_input: { file_path: info.filePath } } };
  if (info.op === "write")
    return {
      sub: "pre-write",
      payload: { tool_name: "Write", tool_input: { file_path: info.filePath, content: info.content } },
    };
  return {
    sub: "pre-write",
    payload: { tool_name: "Edit", tool_input: { file_path: info.filePath, new_string: info.newString } },
  };
}

function postPayload(info, content) {
  if (info.op === "read")
    return {
      sub: "post-read",
      payload: {
        tool_name: "Read",
        tool_input: { file_path: info.filePath },
        tool_output: content == null ? undefined : { content },
      },
    };
  if (info.op === "write")
    return {
      sub: "post-write",
      payload: { tool_name: "Write", tool_input: { file_path: info.filePath, content: info.content } },
    };
  return {
    sub: "post-write",
    payload: { tool_name: "Edit", tool_input: { file_path: info.filePath, new_string: info.newString } },
  };
}

export default function (pi) {
  const cwd = pi?.ctx?.cwd || process.cwd();
  const pending = new Map();
  const keyOf = (event) => event?.toolCallId ?? event?.id ?? event?.callId ?? "";

  pi.on?.("session_start", (event) => {
    // Skip hot-reloads so an extension reload mid-task doesn't reset the
    // ephemeral session state; every genuinely new/resumed session starts fresh.
    if (event?.reason === "reload") return;
    void runMink("session-start", null, cwd);
  });
  pi.on?.("agent_end", () => {
    void runMink("session-stop", null, cwd);
  });
  pi.on?.("session_shutdown", () => {
    void runMink("session-stop", null, cwd);
  });

  pi.on?.("tool_call", async (event) => {
    const info = toolInfo(event);
    if (!info) return;
    const { sub, payload } = prePayload(info);
    const { err } = await runMink(sub, payload, cwd);
    if (err) pending.set(keyOf(event), err);
  });

  // Build the Pi tool_result return value. A compression \`replacement\` (a hook's
  // stdout) SUBSTITUTES the tool output; \`advisoryParts\` (hook stderr) are
  // appended as an extra text block — the parity of Claude feeding hook stderr
  // back. Returns undefined when nothing changes, leaving Pi's result intact.
  const buildResult = (event, replacement, advisoryParts) => {
    const advisory = advisoryParts.filter(Boolean).join("\\n");
    if (replacement == null && !advisory) return undefined;
    const base =
      replacement != null
        ? [{ type: "text", text: replacement }]
        : Array.isArray(event.content)
          ? event.content
          : typeof event.content === "string"
            ? [{ type: "text", text: event.content }]
            : [];
    const content = advisory ? [...base, { type: "text", text: advisory }] : base;
    return { content, details: event.details, isError: event.isError };
  };

  pi.on?.("tool_result", async (event) => {
    const info = toolInfo(event);
    if (info) {
      // File ops: post-read/post-write record state; a large whole-file read may
      // also emit a reversible compression replacement on stdout.
      const { sub, payload } = postPayload(info, resultContent(event));
      const post = await runMink(sub, payload, cwd);
      const pre = pending.get(keyOf(event)) ?? "";
      pending.delete(keyOf(event));
      return buildResult(event, parseReplacement(post.out), [pre, post.err]);
    }

    // Non-file tools (Bash/Grep/Glob/MCP): route the output text through the
    // post-tool compression hook and substitute its reversible replacement. The
    // original is cached host-side, retrievable via \`mink retrieve\`.
    const canon = compressibleName(event);
    if (!canon) return;
    const content = resultContent(event);
    if (content == null) return;
    const post = await runMink(
      "post-tool",
      { tool_name: canon, tool_output: { content } },
      cwd
    );
    return buildResult(event, parseReplacement(post.out), [post.err]);
  });
}
`;
}

// ── Guidance skill ───────────────────────────────────────────────────────────
// Pi has no automatic project-rules file (CLAUDE.md / AGENTS.md equivalent), so
// the guidance Mink gives the assistant is delivered as a Pi skill instead.

const PI_GUIDANCE_SKILL = `---
name: mink
description: Mink context management is active in this project. Read this to understand how Mink memory, write enforcement, and note capture work under Pi.
---

# Mink — context management for this project

This project uses **Mink** (\`@drewpayment/mink\`) for cross-session context management.

## How it works
- Mink runs automatically through a Pi extension at \`.pi/extensions/mink.ts\` that hooks session start/stop and every read/edit/write tool call, plus Bash/Grep/Glob/MCP results.
- Large tool outputs may be transparently replaced with a compact, reversible summary; if you need the full original, fetch it with \`mink retrieve <token>\` (the token appears in the summary).
- All state lives in \`~/.mink/\` on the user's machine — **not** in this repository. Do not create or write to any in-repo state directory (no \`.wolf/\`, \`.mink/\`, etc.).
- Read intelligence, write enforcement, bug memory, and the token ledger are handled by the extension. You do not need to manually read or update any state files.
- Mink shares one \`~/.mink/\` state across every assistant wired to this project, so history is unified whether the user runs Pi or another assistant.

## When to act on Mink
- If the user asks to "save a note", "remember this", "log this to my wiki", or similar, use the \`mink-note\` skill (\`/skill:mink-note\`) — it captures into the user's \`~/.mink/\` vault.
- If the extension surfaces a learning, past bug, or repeat-read warning in context, treat that as authoritative project memory and follow it.
- The \`mink dashboard\` and \`mink agent\` commands are user tools — do not invoke them on the user's behalf.
`;

function resolveSkillsSourceDir(): string {
  // Walk up until we find a package root that contains skills/ — works from
  // src/core/agent-pi.ts (dev) and dist/cli.js (installed), which sit at
  // different depths relative to the package root.
  let dir = dirname(new URL(import.meta.url).pathname);
  while (true) {
    if (existsSync(join(dir, "package.json")) && existsSync(join(dir, "skills"))) {
      return join(dir, "skills");
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(dirname(new URL(import.meta.url).pathname), "../../skills");
}

export interface PiInstallResult {
  extensionPath: string;
  guidancePath: string;
  notePath: string | null;
}

export function installPi(cwd: string, cliPath: string): PiInstallResult {
  const extensionPath = piExtensionPath(cwd);
  mkdirSync(dirname(extensionPath), { recursive: true });
  atomicWriteText(extensionPath, buildPiExtension(cliPath));

  const guidancePath = piGuidanceSkillPath(cwd);
  mkdirSync(dirname(guidancePath), { recursive: true });
  atomicWriteText(guidancePath, PI_GUIDANCE_SKILL);

  // Mirror the note-capture skill into Pi's skill directory so the single
  // source of truth (skills/mink-note) is reused rather than duplicated.
  let notePath: string | null = null;
  try {
    const src = join(resolveSkillsSourceDir(), "mink-note", "SKILL.md");
    if (existsSync(src)) {
      notePath = piNoteSkillPath(cwd);
      mkdirSync(dirname(notePath), { recursive: true });
      copyFileSync(src, notePath);
    }
  } catch {
    // Note skill is non-critical — the extension and guidance still work.
    notePath = null;
  }

  return { extensionPath, guidancePath, notePath };
}

export function removePi(cwd: string): void {
  for (const p of [
    piExtensionPath(cwd),
    join(cwd, ".pi", "skills", "mink"),
    join(cwd, ".pi", "skills", "mink-note"),
  ]) {
    try {
      rmSync(p, { recursive: true, force: true });
    } catch {
      // best-effort
    }
  }
}
